# Generated by Django 4.2 on 2025-04-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_alter_task_assignees"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name"]},
        ),
    ]
